### ISSUE TITLE
autoload.php

### ISSUE THREAD

**Issue by Daltontastic** [dustinrue/PHP-XboxLiveClient#1]
Where is it? I removed those includes now all I get is

Couldn't go with u/p with message 'Unable to fetch initial token, Location not found'

**Comment by dustinrue** [comment]
Running composer up will recreate the file. If you continue to have issues with that error you need to check the security page for your account as it's then likely you're being blocked. This should be a direct link - https://account.live.com/Activity?mkt=en-US&refd=account.microsoft.com&refp=security
